//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminRegistration> AdminRegistrations { get; set; }
        public virtual DbSet<ChapterMaster> ChapterMasters { get; set; }
        public virtual DbSet<LearnerProfile> LearnerProfiles { get; set; }
        public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }
        public virtual DbSet<TopicMaster> TopicMasters { get; set; }
        public virtual DbSet<ViewStatus> ViewStatus1 { get; set; }
    
        public virtual ObjectResult<AdminRegistration> ADMINREG_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminRegistration>("ADMINREG_ALL");
        }
    
        public virtual ObjectResult<AdminRegistration> ADMINREG_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminRegistration>("ADMINREG_ALL", mergeOption);
        }
    
        public virtual int ADMINREG_DELETE(string eMAIL)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINREG_DELETE", eMAILParameter);
        }
    
        public virtual ObjectResult<ADMINREG_GETUSER_Result> ADMINREG_GETUSER(string eMAIL)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADMINREG_GETUSER_Result>("ADMINREG_GETUSER", eMAILParameter);
        }
    
        public virtual int ADMINREG_INSERT(string eMAIL, string fNAME, string lNAME, string pASSWORD)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fNAMEParameter = fNAME != null ?
                new ObjectParameter("FNAME", fNAME) :
                new ObjectParameter("FNAME", typeof(string));
    
            var lNAMEParameter = lNAME != null ?
                new ObjectParameter("LNAME", lNAME) :
                new ObjectParameter("LNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINREG_INSERT", eMAILParameter, fNAMEParameter, lNAMEParameter, pASSWORDParameter);
        }
    
        public virtual int ADMINREG_UPDATE(string eMAIL, string fNAME, string lNAME, string pASSWORD)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fNAMEParameter = fNAME != null ?
                new ObjectParameter("FNAME", fNAME) :
                new ObjectParameter("FNAME", typeof(string));
    
            var lNAMEParameter = lNAME != null ?
                new ObjectParameter("LNAME", lNAME) :
                new ObjectParameter("LNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADMINREG_UPDATE", eMAILParameter, fNAMEParameter, lNAMEParameter, pASSWORDParameter);
        }
    
        public virtual ObjectResult<ChapterMaster> CHAPTERMASTER_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChapterMaster>("CHAPTERMASTER_ALL");
        }
    
        public virtual ObjectResult<ChapterMaster> CHAPTERMASTER_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChapterMaster>("CHAPTERMASTER_ALL", mergeOption);
        }
    
        public virtual int CHAPTERMASTER_DELETE(string cNAME)
        {
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHAPTERMASTER_DELETE", cNAMEParameter);
        }
    
        public virtual int CHAPTERMASTER_INSERT(string cNAME, Nullable<int> sUBID, Nullable<System.DateTime> lASTUP)
        {
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHAPTERMASTER_INSERT", cNAMEParameter, sUBIDParameter, lASTUPParameter);
        }
    
        public virtual int CHAPTERMASTER_UPDATE(string cNAME, Nullable<int> sUBID, Nullable<System.DateTime> lASTUP)
        {
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHAPTERMASTER_UPDATE", cNAMEParameter, sUBIDParameter, lASTUPParameter);
        }
    
        public virtual ObjectResult<LearnerProfile> LEARNPROF_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LearnerProfile>("LEARNPROF_ALL");
        }
    
        public virtual ObjectResult<LearnerProfile> LEARNPROF_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LearnerProfile>("LEARNPROF_ALL", mergeOption);
        }
    
        public virtual int LEARNPROF_DELETE(string eMAIL)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LEARNPROF_DELETE", eMAILParameter);
        }
    
        public virtual int LEARNPROF_INSERT(string eMAIL, string fNAME, string lNAME, Nullable<System.DateTime> dOB, string gENDER, string rEM, string pASSWORD, string sTATUS)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fNAMEParameter = fNAME != null ?
                new ObjectParameter("FNAME", fNAME) :
                new ObjectParameter("FNAME", typeof(string));
    
            var lNAMEParameter = lNAME != null ?
                new ObjectParameter("LNAME", lNAME) :
                new ObjectParameter("LNAME", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            var rEMParameter = rEM != null ?
                new ObjectParameter("REM", rEM) :
                new ObjectParameter("REM", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LEARNPROF_INSERT", eMAILParameter, fNAMEParameter, lNAMEParameter, dOBParameter, gENDERParameter, rEMParameter, pASSWORDParameter, sTATUSParameter);
        }
    
        public virtual int LEARNPROF_UPDATE(string eMAIL, string fNAME, string lNAME, Nullable<System.DateTime> dOB, string gENDER, string rEM, string pASSWORD, string sTATUS)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fNAMEParameter = fNAME != null ?
                new ObjectParameter("FNAME", fNAME) :
                new ObjectParameter("FNAME", typeof(string));
    
            var lNAMEParameter = lNAME != null ?
                new ObjectParameter("LNAME", lNAME) :
                new ObjectParameter("LNAME", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            var rEMParameter = rEM != null ?
                new ObjectParameter("REM", rEM) :
                new ObjectParameter("REM", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LEARNPROF_UPDATE", eMAILParameter, fNAMEParameter, lNAMEParameter, dOBParameter, gENDERParameter, rEMParameter, pASSWORDParameter, sTATUSParameter);
        }
    
        public virtual ObjectResult<SubjectMaster> SUBMASTER_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubjectMaster>("SUBMASTER_ALL");
        }
    
        public virtual ObjectResult<SubjectMaster> SUBMASTER_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubjectMaster>("SUBMASTER_ALL", mergeOption);
        }
    
        public virtual int SUBMASTER_DELETE(Nullable<int> sUBID)
        {
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUBMASTER_DELETE", sUBIDParameter);
        }
    
        public virtual int SUBMASTER_INSERT(Nullable<int> sUBID, string sUBNAME, Nullable<System.DateTime> lASTUP, string dOMAIN)
        {
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var sUBNAMEParameter = sUBNAME != null ?
                new ObjectParameter("SUBNAME", sUBNAME) :
                new ObjectParameter("SUBNAME", typeof(string));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            var dOMAINParameter = dOMAIN != null ?
                new ObjectParameter("DOMAIN", dOMAIN) :
                new ObjectParameter("DOMAIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUBMASTER_INSERT", sUBIDParameter, sUBNAMEParameter, lASTUPParameter, dOMAINParameter);
        }
    
        public virtual int SUBMASTER_UPDATE(Nullable<int> sUBID, string sUBNAME, Nullable<System.DateTime> lASTUP, string dOMAIN)
        {
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var sUBNAMEParameter = sUBNAME != null ?
                new ObjectParameter("SUBNAME", sUBNAME) :
                new ObjectParameter("SUBNAME", typeof(string));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            var dOMAINParameter = dOMAIN != null ?
                new ObjectParameter("DOMAIN", dOMAIN) :
                new ObjectParameter("DOMAIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUBMASTER_UPDATE", sUBIDParameter, sUBNAMEParameter, lASTUPParameter, dOMAINParameter);
        }
    
        public virtual ObjectResult<TopicMaster> TOPICMASTER_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopicMaster>("TOPICMASTER_ALL");
        }
    
        public virtual ObjectResult<TopicMaster> TOPICMASTER_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopicMaster>("TOPICMASTER_ALL", mergeOption);
        }
    
        public virtual int TOPICMASTER_DELETE(string tNAME)
        {
            var tNAMEParameter = tNAME != null ?
                new ObjectParameter("TNAME", tNAME) :
                new ObjectParameter("TNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TOPICMASTER_DELETE", tNAMEParameter);
        }
    
        public virtual int TOPICMASTER_INSERT(string tNAME, Nullable<int> sUBID, string cNAME, Nullable<System.DateTime> lASTUP, string cONTURL)
        {
            var tNAMEParameter = tNAME != null ?
                new ObjectParameter("TNAME", tNAME) :
                new ObjectParameter("TNAME", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            var cONTURLParameter = cONTURL != null ?
                new ObjectParameter("CONTURL", cONTURL) :
                new ObjectParameter("CONTURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TOPICMASTER_INSERT", tNAMEParameter, sUBIDParameter, cNAMEParameter, lASTUPParameter, cONTURLParameter);
        }
    
        public virtual int TOPICMASTER_UPDATE(string tNAME, Nullable<int> sUBID, string cNAME, Nullable<System.DateTime> lASTUP, string cONTURL)
        {
            var tNAMEParameter = tNAME != null ?
                new ObjectParameter("TNAME", tNAME) :
                new ObjectParameter("TNAME", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var lASTUPParameter = lASTUP.HasValue ?
                new ObjectParameter("LASTUP", lASTUP) :
                new ObjectParameter("LASTUP", typeof(System.DateTime));
    
            var cONTURLParameter = cONTURL != null ?
                new ObjectParameter("CONTURL", cONTURL) :
                new ObjectParameter("CONTURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TOPICMASTER_UPDATE", tNAMEParameter, sUBIDParameter, cNAMEParameter, lASTUPParameter, cONTURLParameter);
        }
    
        public virtual ObjectResult<ViewStatus> VIEWSTATUS_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewStatus>("VIEWSTATUS_ALL");
        }
    
        public virtual ObjectResult<ViewStatus> VIEWSTATUS_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewStatus>("VIEWSTATUS_ALL", mergeOption);
        }
    
        public virtual int VIEWSTATUS_DELETE(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VIEWSTATUS_DELETE", iDParameter);
        }
    
        public virtual int VIEWSTATUS_INSERT(Nullable<int> iD, string eMAIL, Nullable<int> sUBID, string cNAME, string tNAME, Nullable<System.DateTime> vTIME, string cOMMENT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var tNAMEParameter = tNAME != null ?
                new ObjectParameter("TNAME", tNAME) :
                new ObjectParameter("TNAME", typeof(string));
    
            var vTIMEParameter = vTIME.HasValue ?
                new ObjectParameter("VTIME", vTIME) :
                new ObjectParameter("VTIME", typeof(System.DateTime));
    
            var cOMMENTParameter = cOMMENT != null ?
                new ObjectParameter("COMMENT", cOMMENT) :
                new ObjectParameter("COMMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VIEWSTATUS_INSERT", iDParameter, eMAILParameter, sUBIDParameter, cNAMEParameter, tNAMEParameter, vTIMEParameter, cOMMENTParameter);
        }
    
        public virtual int VIEWSTATUS_UPDATE(Nullable<int> iD, string eMAIL, Nullable<int> sUBID, string cNAME, string tNAME, Nullable<System.DateTime> vTIME, string cOMMENT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sUBIDParameter = sUBID.HasValue ?
                new ObjectParameter("SUBID", sUBID) :
                new ObjectParameter("SUBID", typeof(int));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            var tNAMEParameter = tNAME != null ?
                new ObjectParameter("TNAME", tNAME) :
                new ObjectParameter("TNAME", typeof(string));
    
            var vTIMEParameter = vTIME.HasValue ?
                new ObjectParameter("VTIME", vTIME) :
                new ObjectParameter("VTIME", typeof(System.DateTime));
    
            var cOMMENTParameter = cOMMENT != null ?
                new ObjectParameter("COMMENT", cOMMENT) :
                new ObjectParameter("COMMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VIEWSTATUS_UPDATE", iDParameter, eMAILParameter, sUBIDParameter, cNAMEParameter, tNAMEParameter, vTIMEParameter, cOMMENTParameter);
        }
    }
}
